/*
 * This file is generated by jOOQ.
 */
package com.apon.elitefour.database;


import com.apon.elitefour.database.tables.FlywaySchemaHistory;
import com.apon.elitefour.database.tables.List;
import com.apon.elitefour.database.tables.ListItem;
import com.apon.elitefour.database.tables.ListItemEliminated;
import com.apon.elitefour.database.tables.Status;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index LIST_PKEY = Indexes0.LIST_PKEY;
    public static final Index LIST_ITEM_PKEY = Indexes0.LIST_ITEM_PKEY;
    public static final Index LIST_ITEM_ELIMINATED_PKEY = Indexes0.LIST_ITEM_ELIMINATED_PKEY;
    public static final Index STATUS_PKEY = Indexes0.STATUS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index LIST_PKEY = Internal.createIndex("list_pkey", List.LIST, new OrderField[] { List.LIST.ID }, true);
        public static Index LIST_ITEM_PKEY = Internal.createIndex("list_item_pkey", ListItem.LIST_ITEM, new OrderField[] { ListItem.LIST_ITEM.ID }, true);
        public static Index LIST_ITEM_ELIMINATED_PKEY = Internal.createIndex("list_item_eliminated_pkey", ListItemEliminated.LIST_ITEM_ELIMINATED, new OrderField[] { ListItemEliminated.LIST_ITEM_ELIMINATED.ITEM_ID, ListItemEliminated.LIST_ITEM_ELIMINATED.ELIMINATED_ITEM_ID }, true);
        public static Index STATUS_PKEY = Internal.createIndex("status_pkey", Status.STATUS, new OrderField[] { Status.STATUS.ID }, true);
    }
}
