/*
 * This file is generated by jOOQ.
 */
package com.apon.elitefour.database;


import com.apon.elitefour.database.tables.*;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.list</code>.
     */
    public static final List LIST = List.LIST;

    /**
     * The table <code>public.list_item</code>.
     */
    public static final ListItem LIST_ITEM = ListItem.LIST_ITEM;

    /**
     * The table <code>public.list_item_eliminated</code>.
     */
    public static final ListItemEliminated LIST_ITEM_ELIMINATED = ListItemEliminated.LIST_ITEM_ELIMINATED;

    /**
     * The table <code>public.status</code>.
     */
    public static final Status STATUS = Status.STATUS;
}
