/*
 * This file is generated by jOOQ.
 */
package com.apon.elitefour.database.tables.pojos;


import javax.annotation.processing.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListItem implements Serializable {

    private static final long serialVersionUID = 771905701;

    private final Integer id;
    private final String  name;
    private final Integer listId;

    public ListItem(ListItem value) {
        this.id = value.id;
        this.name = value.name;
        this.listId = value.listId;
    }

    public ListItem(
        Integer id,
        String  name,
        Integer listId
    ) {
        this.id = id;
        this.name = name;
        this.listId = listId;
    }

    public Integer getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public Integer getListId() {
        return this.listId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ListItem (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(listId);

        sb.append(")");
        return sb.toString();
    }
}
