/*
 * This file is generated by jOOQ.
 */
package com.apon.elitefour.database.tables.records;


import com.apon.elitefour.database.tables.ListItemEliminated;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListItemEliminatedRecord extends UpdatableRecordImpl<ListItemEliminatedRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -156177867;

    /**
     * Setter for <code>public.list_item_eliminated.item_id</code>.
     */
    public ListItemEliminatedRecord setItemId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.list_item_eliminated.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.list_item_eliminated.eliminated_item_id</code>.
     */
    public ListItemEliminatedRecord setEliminatedItemId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.list_item_eliminated.eliminated_item_id</code>.
     */
    public Integer getEliminatedItemId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ListItemEliminated.LIST_ITEM_ELIMINATED.ITEM_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ListItemEliminated.LIST_ITEM_ELIMINATED.ELIMINATED_ITEM_ID;
    }

    @Override
    public Integer component1() {
        return getItemId();
    }

    @Override
    public Integer component2() {
        return getEliminatedItemId();
    }

    @Override
    public Integer value1() {
        return getItemId();
    }

    @Override
    public Integer value2() {
        return getEliminatedItemId();
    }

    @Override
    public ListItemEliminatedRecord value1(Integer value) {
        setItemId(value);
        return this;
    }

    @Override
    public ListItemEliminatedRecord value2(Integer value) {
        setEliminatedItemId(value);
        return this;
    }

    @Override
    public ListItemEliminatedRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListItemEliminatedRecord
     */
    public ListItemEliminatedRecord() {
        super(ListItemEliminated.LIST_ITEM_ELIMINATED);
    }

    /**
     * Create a detached, initialised ListItemEliminatedRecord
     */
    public ListItemEliminatedRecord(Integer itemId, Integer eliminatedItemId) {
        super(ListItemEliminated.LIST_ITEM_ELIMINATED);

        set(0, itemId);
        set(1, eliminatedItemId);
    }
}
