/*
 * This file is generated by jOOQ.
 */
package com.apon.elitefour.database.tables.records;


import com.apon.elitefour.database.tables.List;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListRecord extends UpdatableRecordImpl<ListRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 489634513;

    /**
     * Setter for <code>public.list.id</code>.
     */
    public ListRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.list.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.list.name</code>.
     */
    public ListRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.list.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.list.status_id</code>.
     */
    public ListRecord setStatusId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.list.status_id</code>.
     */
    public Integer getStatusId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return List.LIST.ID;
    }

    @Override
    public Field<String> field2() {
        return List.LIST.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return List.LIST.STATUS_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getStatusId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getStatusId();
    }

    @Override
    public ListRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ListRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ListRecord value3(Integer value) {
        setStatusId(value);
        return this;
    }

    @Override
    public ListRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListRecord
     */
    public ListRecord() {
        super(List.LIST);
    }

    /**
     * Create a detached, initialised ListRecord
     */
    public ListRecord(Integer id, String name, Integer statusId) {
        super(List.LIST);

        set(0, id);
        set(1, name);
        set(2, statusId);
    }
}
